const userquestions = [
    {
      category: "General Knowledge",
      question: "What is the capital of Pakistan?",
      options: ["Karachi", "Islamabad", "Lahore", "Peshawar"],
      answer: "Islamabad",
    },
    {
      category: "General Knowledge",
      question: "Who is the founder of Pakistan?",
      options: ["Allama Iqbal", "Liaquat Ali Khan", "Quaid-e-Azam", "Sir Syed Ahmed Khan"],
      answer: "Quaid-e-Azam",
    },
    {
      category: "General Knowledge",
      question: "What is the national language of Pakistan?",
      options: ["Urdu", "Punjabi", "Sindhi", "Pashto"],
      answer: "Urdu",
    },
    {
      category: "General Knowledge",
      question: "What is the national flower of Pakistan?",
      options: ["Rose", "Jasmine", "Sunflower", "Lily"],
      answer: "Jasmine",
    },
    {
      category: "General Knowledge",
      question: "Which city is known as the 'City of Lights' in Pakistan?",
      options: ["Lahore", "Karachi", "Islamabad", "Peshawar"],
      answer: "Karachi",
    },
    {
      category: "General Knowledge",
      question: "What is the national animal of Pakistan?",
      options: ["Markhor", "Lion", "Tiger", "Peacock"],
      answer: "Markhor",
    },
    {
      category: "General Knowledge",
      question: "What is the total number of provinces in Pakistan?",
      options: ["3", "4", "5", "6"],
      answer: "4",
    },
    {
      category: "General Knowledge",
      question: "Which is the largest province of Pakistan by area?",
      options: ["Sindh", "Punjab", "Balochistan", "Khyber Pakhtunkhwa"],
      answer: "Balochistan",
    },
    {
      category: "General Knowledge",
      question: "Who wrote Pakistan's national anthem?",
      options: ["Allama Iqbal", "Hafeez Jalandhari", "Faiz Ahmed Faiz", "Ahmed Faraz"],
      answer: "Hafeez Jalandhari",
    },
    {
      category: "General Knowledge",
      question: "When did Pakistan become independent?",
      options: ["14th August 1947", "15th August 1947", "14th August 1948", "15th August 1948"],
      answer: "14th August 1947",
    },
    {
      category: "General Knowledge",
      question: "Who was the first Prime Minister of Pakistan?",
      options: ["Liaquat Ali Khan", "Ayub Khan", "Zulfiqar Ali Bhutto", "Muhammad Ali Jinnah"],
      answer: "Liaquat Ali Khan",
    },
    {
      category: "General Knowledge",
      question: "What is the largest city in Pakistan by population?",
      options: ["Islamabad", "Karachi", "Lahore", "Faisalabad"],
      answer: "Karachi",
    },
    {
      category: "General Knowledge",
      question: "In which year was the Constitution of Pakistan enacted?",
      options: ["1947", "1956", "1962", "1973"],
      answer: "1973",
    },
    {
      category: "General Knowledge",
      question: "What is the national sport of Pakistan?",
      options: ["Hockey", "Cricket", "Football", "Kabaddi"],
      answer: "Hockey",
    },
    {
      category: "General Knowledge",
      question: "Which dam is the largest in Pakistan?",
      options: ["Mangla Dam", "Tarbela Dam", "Warsak Dam", "Hub Dam"],
      answer: "Tarbela Dam",
    },
    {
      category: "General Knowledge",
      question: "What is the currency of Pakistan?",
      options: ["Pakistani Rupee", "Indian Rupee", "Taka", "Riyal"],
      answer: "Pakistani Rupee",
    },
    {
      category: "General Knowledge",
      question: "Who is known as the Poet of the East in Pakistan?",
      options: ["Faiz Ahmed Faiz", "Allama Iqbal", "Ahmed Faraz", "Mirza Ghalib"],
      answer: "Allama Iqbal",
    },
    {
      category: "General Knowledge",
      question: "What is the total area of Pakistan?",
      options: ["796,095 sq km", "800,000 sq km", "750,000 sq km", "700,000 sq km"],
      answer: "796,095 sq km",
    },
    {
      category: "General Knowledge",
      question: "Which city is called the 'City of Gardens' in Pakistan?",
      options: ["Lahore", "Karachi", "Islamabad", "Rawalpindi"],
      answer: "Lahore",
    },
    {
      category: "General Knowledge",
      question: "Which river is the longest in Pakistan?",
      options: ["Chenab River", "Indus River", "Ravi River", "Jhelum River"],
      answer: "Indus River",
    },
    {
      category: "General Knowledge",
      question: "Who was the first President of Pakistan?",
      options: ["Iskander Mirza", "Ayub Khan", "Zulfiqar Ali Bhutto", "Liaquat Ali Khan"],
      answer: "Iskander Mirza",
    },
    {
      category: "General Knowledge",
      question: "Which mountain range is located in the north of Pakistan?",
      options: ["Himalayas", "Karakoram", "Hindu Kush", "All of these"],
      answer: "All of these",
    },
    {
      category: "General Knowledge",
      question: "Where is Minar-e-Pakistan located?",
      options: ["Karachi", "Lahore", "Islamabad", "Peshawar"],
      answer: "Lahore",
    },
    {
      category: "General Knowledge",
      question: "What is the national drink of Pakistan?",
      options: ["Lassi", "Chai", "Rooh Afza", "Sugarcane Juice"],
      answer: "Sugarcane Juice",
    },
    {
      category: "General Knowledge",
      question: "Which Pakistani scientist won the Nobel Prize in Physics?",
      options: ["Abdus Salam", "Dr. AQ Khan", "Abdul Sattar Edhi", "Malala Yousafzai"],
      answer: "Abdus Salam",
    },
    {
      category: "General Knowledge",
      question: "What is the name of Pakistan's national airline?",
      options: ["PIA", "Airblue", "Shaheen Air", "Indus Air"],
      answer: "PIA",
    },
    {
      category: "General Knowledge",
      question: "Which province of Pakistan has the largest population?",
      options: ["Sindh", "Punjab", "Balochistan", "Khyber Pakhtunkhwa"],
      answer: "Punjab",
    },
    {
      category: "General Knowledge",
      question: "Who designed Pakistan's national flag?",
      options: ["Allama Iqbal", "Ameer-ud-Din Khidwai", "Liaquat Ali Khan", "Muhammad Ali Jinnah"],
      answer: "Ameer-ud-Din Khidwai",
    },
    {
      category: "General Knowledge",
      question: "Which sea borders Pakistan to the south?",
      options: ["Arabian Sea", "Bay of Bengal", "Red Sea", "Caspian Sea"],
      answer: "Arabian Sea",
    },
    {
      category: "General Knowledge",
      question: "When was the first Islamic Summit Conference held in Pakistan?",
      options: ["1970", "1974", "1976", "1980"],
      answer: "1974",
    },
      {
        category: "HTML",
        question: "What does HTML stand for?",
        options: [
          "Hyper Text Markup Language",
          "Hyperlinks and Text Markup Language",
          "Home Tool Markup Language",
          "Hyper Transfer Markup Language",
        ],
        answer: "Hyper Text Markup Language",
      },
      {
        category: "HTML",
        question: "Which HTML tag is used to define an unordered list?",
        options: ["<ul>", "<ol>", "<li>", "<list>"],
        answer: "<ul>",
      },
      {
        category: "HTML",
        question: "Which tag is used to create a hyperlink in HTML?",
        options: ["<a>", "<link>", "<href>", "<hyperlink>"],
        answer: "<a>",
      },
      {
        category: "HTML",
        question: "Which attribute is used to provide a unique identifier to an HTML element?",
        options: ["id", "class", "name", "key"],
        answer: "id",
      },
      {
        category: "HTML",
        question: "What is the purpose of the <title> tag in HTML?",
        options: [
          "To define the document's title shown in the browser tab",
          "To create a heading on the webpage",
          "To display a tooltip when hovering",
          "To define a section in the document",
        ],
        answer: "To define the document's title shown in the browser tab",
      },
      {
        category: "HTML",
        question: "Which is the correct way to specify an image in HTML?",
        options: [
          '<img src="image.jpg" alt="Description">',
          '<img href="image.jpg" title="Description">',
          '<image src="image.jpg" alt="Description">',
          '<image href="image.jpg" title="Description">',
        ],
        answer: '<img src="image.jpg" alt="Description">',
      },
      {
        category: "HTML",
        question: "What is the default file extension for HTML files?",
        options: [".html", ".htm", ".xml", ".txt"],
        answer: ".html",
      },
      {
        category: "HTML",
        question: "Which HTML tag is used to define a table row?",
        options: ["<tr>", "<td>", "<table>", "<th>"],
        answer: "<tr>",
      },
      {
        category: "HTML",
        question: "Which tag is used to define the largest heading in HTML?",
        options: ["<h1>", "<heading>", "<head>", "<h6>"],
        answer: "<h1>",
      },
      {
        category: "HTML",
        question: "Which attribute is used to specify the URL of a link in the <a> tag?",
        options: ["href", "src", "link", "url"],
        answer: "href",
      },
      {
        category: "HTML",
        question: "What does the <br> tag do in HTML?",
        options: [
          "Creates a line break",
          "Adds a bold text",
          "Creates a blank space",
          "Creates a horizontal line",
        ],
        answer: "Creates a line break",
      },
      {
        category: "HTML",
        question: "Which HTML tag is used to add metadata to a webpage?",
        options: ["<meta>", "<head>", "<data>", "<info>"],
        answer: "<meta>",
      },
      {
        category: "HTML",
        question: "Which HTML element is used to create a dropdown list?",
        options: ["<select>", "<input>", "<dropdown>", "<list>"],
        answer: "<select>",
      },
      {
        category: "HTML",
        question: "Which tag is used to add a comment in HTML?",
        options: [
          "<!-- Comment -->",
          "// Comment",
          "# Comment",
          "<comment>Comment</comment>",
        ],
        answer: "<!-- Comment -->",
      },
      {
        category: "HTML",
        question: "Which attribute is used to open a link in a new tab?",
        options: ['target="_blank"', 'rel="newtab"', 'href="newtab"', 'window="new"'],
        answer: 'target="_blank"',
      },
      {
        category: "HTML",
        question: "Which tag is used to embed a video in HTML?",
        options: ["<video>", "<embed>", "<iframe>", "<media>"],
        answer: "<video>",
      },
      {
        category: "HTML",
        question: "Which tag is used to define a form in HTML?",
        options: ["<form>", "<input>", "<fieldset>", "<submit>"],
        answer: "<form>",
      },
      {
        category: "HTML",
        question: "Which attribute is used to set the background color of an HTML element?",
        options: ["style", "bgcolor", "background", "color"],
        answer: "style",
      },
      {
        category: "HTML",
        question: "Which HTML tag is used to create a numbered list?",
        options: ["<ol>", "<ul>", "<li>", "<list>"],
        answer: "<ol>",
      },
      {
        category: "HTML",
        question: "Which HTML5 element is used to play audio files?",
        options: ["<audio>", "<sound>", "<media>", "<music>"],
        answer: "<audio>",
      },
      {
        category: "General Knowledge",
        question: "What is the national flower of Pakistan?",
        options: ["Jasmine", "Rose", "Sunflower", "Lily"],
        answer: "Jasmine",
      },
      {
        category: "General Knowledge",
        question: "Who was the founder of Pakistan's nuclear program?",
        options: ["Abdus Salam", "Dr. Abdul Qadeer Khan", "Zulfiqar Ali Bhutto", "Pervez Musharraf"],
        answer: "Dr. Abdul Qadeer Khan",
      },
      {
        category: "General Knowledge",
        question: "Which is the highest peak in Pakistan?",
        options: ["Nanga Parbat", "K2", "Rakaposhi", "Tirich Mir"],
        answer: "K2",
      },
      {
        category: "General Knowledge",
        question: "Which city is known as the 'City of Lights' in Pakistan?",
        options: ["Lahore", "Karachi", "Islamabad", "Peshawar"],
        answer: "Karachi",
      },
      {
        category: "General Knowledge",
        question: "What is the national language of Pakistan?",
        options: ["Urdu", "Punjabi", "Sindhi", "Pashto"],
        answer: "Urdu",
      },
      {
        category: "General Knowledge",
        question: "Which province is the largest by area in Pakistan?",
        options: ["Punjab", "Sindh", "Balochistan", "Khyber Pakhtunkhwa"],
        answer: "Balochistan",
      },
      {
        category: "General Knowledge",
        question: "Which is the oldest university in Pakistan?",
        options: ["University of the Punjab", "Karachi University", "Quaid-e-Azam University", "Peshawar University"],
        answer: "University of the Punjab",
      },
      {
        category: "General Knowledge",
        question: "What is the full form of NADRA?",
        options: [
          "National Database and Registration Authority",
          "National Development and Regulation Authority",
          "National Defense and Registration Agency",
          "None of the above",
        ],
        answer: "National Database and Registration Authority",
      },
      {
        category: "General Knowledge",
        question: "When did Pakistan become a member of the United Nations?",
        options: ["1947", "1948", "1949", "1950"],
        answer: "1947",
      },
      {
        category: "General Knowledge",
        question: "Which city is famous for the Khewra Salt Mine in Pakistan?",
        options: ["Lahore", "Jehlum", "Rawalpindi", "Karachi"],
        answer: "Jehlum",
      },
      {
        category: "General Knowledge",
        question: "Which region of Pakistan is known as 'Little Kashmir'?",
        options: ["Swat Valley", "Hunza Valley", "Neelum Valley", "Kaghan Valley"],
        answer: "Swat Valley",
      },
      {
        category: "General Knowledge",
        question: "When was the first census conducted in Pakistan?",
        options: ["1947", "1951", "1961", "1971"],
        answer: "1951",
      },
      {
        category: "General Knowledge",
        question: "What is the total number of districts in Pakistan?",
        options: ["120", "154", "160", "170"],
        answer: "160",
      },
      {
        category: "General Knowledge",
        question: "Which Pakistani city is known for its Sufi shrines?",
        options: ["Multan", "Lahore", "Karachi", "Hyderabad"],
        answer: "Multan",
      },
      {
        category: "General Knowledge",
        question: "Which is the largest desert in Pakistan?",
        options: ["Thar Desert", "Cholistan Desert", "Kharan Desert", "Nara Desert"],
        answer: "Thar Desert",
      },
      {
        category: "General Knowledge",
        question: "What is the name of the national anthem of Pakistan?",
        options: ["Qaumi Tarana", "Pak Sar Zameen", "Sohni Dharti", "Dil Dil Pakistan"],
        answer: "Qaumi Tarana",
      },
      {
        category: "General Knowledge",
        question: "Who designed the Minar-e-Pakistan?",
        options: ["Murad Khan", "Naseer Uddin Murat Khan", "Abdur Rehman Chughtai", "None of the above"],
        answer: "Naseer Uddin Murat Khan",
      },
      {
        category: "General Knowledge",
        question: "Which river is known as the lifeline of Pakistan?",
        options: ["Chenab", "Indus", "Jhelum", "Ravi"],
        answer: "Indus",
      },
      {
        category: "General Knowledge",
        question: "Which city is famous for its handmade Ajrak and Sindhi Topi?",
        options: ["Karachi", "Hyderabad", "Sukkur", "Larkana"],
        answer: "Hyderabad",
      },
      {
        category: "General Knowledge",
        question: "What is the name of the Pakistan-India border?",
        options: ["Wagah Border", "Torkham Border", "Durand Line", "Radcliffe Line"],
        answer: "Wagah Border",
      },
    ];




    export default userquestions;